"""Initial migration with wellness models

Revision ID: 7643864aa090
Revises: 
Create Date: 2026-04-16 15:09:54.071426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7643864aa090'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wellness_reminders', sa.Column('daily_goal', sa.Integer(), nullable=True))
    op.add_column('wellness_reminders', sa.Column('unit', sa.String(), nullable=True))
    op.add_column('wellness_reminders', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wellness_reminders', 'weight')
    op.drop_column('wellness_reminders', 'unit')
    op.drop_column('wellness_reminders', 'daily_goal')
    # ### end Alembic commands ###
